[general]
import = ["~/.config/alacritty/tango_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
title = ""
dynamic_title = false
decorations = "Buttonless"

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 18

[keyboard]
bindings = [
    {key="W", mods="Alt", action="Quit"},
    {key="V", mods="Alt", action="Paste"},
    {key="C", mods="Alt", action="Copy"},
]
