local harpoon = require("harpoon")
harpoon:setup()
vim.keymap.set("n", "<leader>mm", function()
	harpoon:list():append()
end)
vim.keymap.set("n", "<leader>fm", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)
