require 'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "json",
        "javascript",
        "typescript",
        "tsx",
        "html",
        "css",
        "markdown",
        "markdown_inline",
        "vim",
        "lua",
        "gitignore",
        "c",
        "cpp",
        "cmake",
        "csv",
        "ninja",
        "rust",
        "python",
        "bash",
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "<C-n>",
            node_incremental = "<C-n>",
            scope_incremental = false,
            node_decremental = "<C-m>",
        },
    },
    auto_install = true,
    ignore_install = {},
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    indent = {
        enable = true,
    },
}
