require("configs.lsp")
require("configs.luasnip")
require("configs.comment")
require("configs.treesitter")
require("configs.lualine")
require("configs.colorscheme")
require("configs.telescope")
require("configs.nvim-tree")
require("configs.indentline")

